export const nacionalidades = [
  { value: 'Afganistán', label: 'Afganistán' },
  { value: 'Albania', label: 'Albania' },
  { value: 'Alemania', label: 'Alemania' },
  { value: 'Andorra', label: 'Andorra' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Argelia', label: 'Argelia' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Armenia', label: 'Armenia' },
  { value: 'Aruba', label: 'Aruba' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaiyán', label: 'Azerbaiyán' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Bangladés', label: 'Bangladés' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Baréin', label: 'Baréin' },
  { value: 'Bélgica', label: 'Bélgica' },
  { value: 'Belice', label: 'Belice' },
  { value: 'Bielorrusia', label: 'Bielorrusia' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Bosnia y Herzegovina', label: 'Bosnia y Herzegovina' },
  { value: 'Brasil', label: 'Brasil' },
  { value: 'Reino Unido', label: 'Reino Unido' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Camerún', label: 'Camerún' },
  { value: 'Canadá', label: 'Canadá' },
  { value: 'República Checa', label: 'República Checa' },
  { value: 'Chile', label: 'Chile' },
  { value: 'China', label: 'China' },
  { value: 'Chipre', label: 'Chipre' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Croacia', label: 'Croacia' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Dinamarca', label: 'Dinamarca' },
  { value: 'República Dominicana', label: 'República Dominicana' },
  { value: 'Dominica', label: 'Dominica' },
  { value: 'Guinea Ecuatorial', label: 'Guinea Ecuatorial' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Egipto', label: 'Egipto' },
  { value: 'Emiratos Árabes Unidos', label: 'Emiratos Árabes Unidos' },
  { value: 'Escocia', label: 'Escocia' },
  { value: 'Eslovaquia', label: 'Eslovaquia' },
  { value: 'Eslovenia', label: 'Eslovenia' },
  { value: 'España', label: 'España' },
  { value: 'Estados Unidos', label: 'Estados Unidos' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Etiopía', label: 'Etiopía' },
  { value: 'Filipinas', label: 'Filipinas' },
  { value: 'Finlandia', label: 'Finlandia' },
  { value: 'Francia', label: 'Francia' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Grecia', label: 'Grecia' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Haití', label: 'Haití' },
  { value: 'India', label: 'India' },
  { value: 'Países Bajos', label: 'Países Bajos' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Hungría', label: 'Hungría' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Irlanda', label: 'Irlanda' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Italia', label: 'Italia' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Japón', label: 'Japón' },
  { value: 'Letonia', label: 'Letonia' },
  { value: 'Líbano', label: 'Líbano' },
  { value: 'Liberia', label: 'Liberia' },
  { value: 'Libia', label: 'Libia' },
  { value: 'Lituania', label: 'Lituania' },
  { value: 'Luxemburgo', label: 'Luxemburgo' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Marruecos', label: 'Marruecos' },
  { value: 'México', label: 'México' },
  { value: 'Moldavia', label: 'Moldavia' },
  { value: 'Mónaco', label: 'Mónaco' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Montenegro', label: 'Montenegro' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Nueva Zelanda', label: 'Nueva Zelanda' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'Corea del Norte', label: 'Corea del Norte' },
  { value: 'Noruega', label: 'Noruega' },
  { value: 'Panamá', label: 'Panamá' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Pakistán', label: 'Pakistán' },
  { value: 'Perú', label: 'Perú' },
  { value: 'Polonia', label: 'Polonia' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Puerto Rico', label: 'Puerto Rico' },
  { value: 'Rumania', label: 'Rumania' },
  { value: 'Rusia', label: 'Rusia' },
  { value: 'Sahara Occidental', label: 'Sahara Occidental' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'San Cristóbal y Nieves', label: 'San Cristóbal y Nieves' },
  { value: 'Santa Lucía', label: 'Santa Lucía' },
  { value: 'San Vicente y las Granadinas', label: 'San Vicente y las Granadinas' },
  { value: 'Senegal', label: 'Senegal' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Siria', label: 'Siria' },
  { value: 'Sudáfrica', label: 'Sudáfrica' },
  { value: 'Suecia', label: 'Suecia' },
  { value: 'Suiza', label: 'Suiza' },
  { value: 'Corea del Sur', label: 'Corea del Sur' },
  { value: 'Surinam', label: 'Surinam' },
  { value: 'Togo', label: 'Togo' },
  { value: 'Turquía', label: 'Turquía' },
  { value: 'Ucrania', label: 'Ucrania' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Vietnam', label: 'Vietnam' },
]
